### ISSUE TITLE
Getting error running unit tests

### ISSUE THREAD

**Issue by syonip** [eddyerburgh/stub-vue-components-babel-rewire#1]
Hi,
I'm getting an error trying to run "npm run unit".
This is the output:

cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run

25 11 2018 09:53:45.706:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
25 11 2018 09:53:45.709:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
25 11 2018 09:53:45.715:INFO [launcher]: Starting browser PhantomJS
25 11 2018 09:53:48.862:INFO [PhantomJS 2.1.1 (Windows 8.0.0)]: Connected on socket 2U4SWTxcCOpszlH8AAAA with id 49652722
25 11 2018 09:53:49.142:WARN [reporter]: SourceMap position not found for trace: undefined
PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  ReferenceError: Can't find variable: exports
  at index.js:12763

PhantomJS 2.1.1 (Windows 8.0.0): Executed 0 of 0 ERROR (0.281 secs / 0 secs)

PhantomJS 2.1.1 (Windows 8.0.0): Executed 0 of 0 ERROR (0.001 secs / 0 secs)

=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn karma ENOENT
    at notFoundError (C:\git\stub-vue-components-babel-rewire\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\git\stub-vue-components-babel-rewire\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\git\stub-vue-components-babel-rewire\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
Emitted 'error' event at:
    at ChildProcess.cp.emit (C:\git\stub-vue-components-babel-rewire\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stub-vue-components-starter@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stub-vue-components-starter@1.0.0 unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by eddyerburgh** [comment]
Try using yarn to install the dependencies. The project has a yarn lock file, and I just did a fresh install to verify everything still works, which it does.

**Comment by syonip** [comment]
thanks @eddyerburgh, tests pass after installing with yarn.
perhaps update the readme to have yarn install instead of npm install :)
